# -*- mode: ruby -*-
# vi: set ft=ruby :

$Boxes = {
  "scalatra-mongo" => ["activator", "jdk7-oracle", "mongodb" ],
  "scalatra-mysql" => ["activator", "jdk7-oracle", "mysql" ],
}

$CurrentBox = "scalatra-mongo"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = $CurrentBox
    v.memory = 512
    v.cpus = 1
  end

  # CentOS7.0 x86_64 minimal (VirtualBoxGuestAddtions 4.3.14)
  config.vm.box = "CentOS7.0_x86_64_minimal"
  config.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"
  
  # http
  config.vm.network :forwarded_port, host: 3000, guest: 8080
  # mongo
  config.vm.network :forwarded_port, host: 28017, guest: 27017

  # config.vm.network "public_network"

  # config.vm.network "private_network", type: "dhcp"
  # config.vm.network "private_network", ip: "192.168.50.4", virtualbox__intnet: true

  config.vm.synced_folder "../source/", "/home/vagrant/app"

  config.vm.provision :shell do |s|
    s.path = "bootstrap.sh"
    s.args = $Boxes[ $CurrentBox ]
  end
end
